Added French to multi-language
opendroneid/receiver-android pull request #59
Opened 2022-05-25 23:14 UTC by Tissy

Being half French, I thought I would add my language translation contribution :)

2022-05-26 01:11 UTC, gabrielcox commented
Wow! 2 languages within hours of each other.  Is your PR with consideration that the Japanese PR with come through first?  That would be ideal to minimize conflicts.  It looks like both have similar changes to strings.xml.  If you haven't already, please have a look at and analyze the Japanese PR to see how it may impact yours.

We really appreciate your contribution.  This is great!

2022-05-26 05:38 UTC, friissoren commented
Thanks. I am currently traveling. Please wait a few days and I can take a look at this. We need to figure out how to deal with the conflicts between this PR and PR #58.

2022-05-26 09:01 UTC, Tissy commented
I did it off the back of the Japanese translation.  Wonder if there is a simple way to perhaps add a menu function to select the required language?

2022-05-26 17:52 UTC, gabrielcox commented
I think the Main Android Settings/Language settings can change it back and forth for testing.   As I understand it, based on your locale setting, within the App, Android will use the language your device is set to if the language strings are there (as the ja and fr PRs add).  The the language file is not there, it will use the "default" strings.xml.

2022-05-27 07:45 UTC, friissoren requested changes
I very much appreciate your contribution. Having more languages supported in the app is a great idea.

However, you clearly didn't compile this :-)

When you fix these few items, could you also rebase the patches on top of the latest master (which now have the Japanese translations) and then squash the two resulting commits? Thanks.

2022-05-27 07:45 UTC, friissoren commented on Android/app/src/main/res/values_fr/strings.xml
> +    <string name="permission_rationale_location">Cette application ne fonctionnera pas sans activer l'accès à la localisation</string>
Please add a "\\" before the "\'" character.
l\\'accès

2022-05-27 07:45 UTC, friissoren commented on Android/app/src/main/res/values_fr/strings.xml
> +    <string name="Show_log_location">Afficher l'emplacement du journal</string>
Please add a "\\" before the "\'" character.
l\\'emplacement

2022-05-27 07:45 UTC, friissoren commented on Android/app/src/main/res/values_fr/strings.xml
> +<!--
The directory path needs to be fixed so Android Studio finds this file. Please change values_fr to values-fr.

2022-05-27 07:48 UTC, friissoren commented
BTW: I tested Gabriel's suspicion that the app language will change with the main phone system language. I tried this on a virtual/emulator device in Android studio. When you change the system language in the settings menu, even an open instance of the app will change the displayed language, when you switch over to it. Very nice.

2022-05-27 11:04 UTC, merged

2022-05-27 11:10 UTC, friissoren commented
Thanks. I have merged this now.

Some of those translations look rather long. You might at some point try to fire up the app and get a transmitter visible in the list, open the Info view and then check the layout of the detailed info view. That view is quite "busy" and might wrap the text strangely when the fields become too long.

2022-05-27 15:37 UTC, Tissy commented
Yup, totally agree.  I shall make some amendments :)